### PR TITLE
Fix ACCCON paged RAM bits.

### LINKED ISSUE #181: Screen clear on Master (shadow and normal flipping)
Planet Nubium development seemed to have a problem with screen clearing:
https://stardot.org.uk/forums/viewtopic.php?p=223299#p223299

> I have been testing the game on BeebEm and JSBeeb rather than a real machine.
> 
> The game uses video double buffering, flipping the video between main and shadow RAM every time it goes around the game loop, so clearing the screen has to clear both main and shadow RAM. This is done by 'PROCcls' line 920, and this line maybe failing on a real MASTER. Because the screen is not being cleared, there is text left on the screen which is repeatedly triggering the collision detection routine on level 1.
> 
> Line 920 moves main and shadow memory into the CPU's memory map, and then uses the BASIC 'CLS' command to clear the screen.
> 
> `920 DEFPROCcls:OSCLI("FX108,1"):CLS:OSCLI("FX108,0"):CLS:VDU19,0,0;0;19,1,0;0;19,2,0;0;19,3,0;0;:ENDPROC
> `

### PR DESCRIPTION
**Pull request by scarybeasts**
Fixes #181 

A specific combination of ACCCON bits was reading/writing the wrong memory area.
Also, fix read of ROMSEL on the Master, which is defined as read/write, not write only.

### CODE REVIEW

File: 6502.js [hunk 1]
```diff
@@ -495,17 +495,33 @@ define(['./utils', './6502.opcodes', './via', './acia', './serial', './tube', '.
                 // as the video circuitry will already be looking at 0x3000 or so above
                 // the offset.
                 this.videoDisplayPage = (b & 1) ? 0x8000 : 0x0000;
-                // The RAM the processor sees for writes when executing OS instructions
-                // is controlled by the "E" bit.
-                this.memStatOffsetByIFetchBank[0xc] = this.memStatOffsetByIFetchBank[0xd] = (b & 2) ? 256 : 0;
+
+                var bitE = !!(b & 2);
```
Comment (mattgodbolt) [inline 6502.js:499]: Thanks for making this clearer.

File: 6502.js [hunk 2]
```diff
@@ -495,17 +495,33 @@ define(['./utils', './6502.opcodes', './via', './acia', './serial', './tube', '.
...
+                    // it's more involved.
+                    if (bitY) {
+                       // If 0xc000 is mapped as RAM, the Master opcode access
+                       // is disabled; follow what normal access does.
+                       this.memLook[i + 256] = this.memLook[i];
+                    } else {
+                       // Master opcode access enabled; bit E determines whether
+                       // it hits shadow RAM or normal RAM. This is independent
+                       // of bit X.
+                       this.memLook[i + 256] = bitE ? 0x8000 : 0;
```
Comment (mattgodbolt) [inline 6502.js:518]: :+1:
